#!/usr/bin/env bash

publicationName=$1

if [ -z "$publicationName" ]
then
  echo "Usage: $0 core|generator" 1>&2
  exit 1
fi

exit

export ORG_GRADLE_PROJECT_publicationName=$1

./gradlew build bintrayUpload