#!/usr/bin/env bash

set -e

./setup-secrets

ORG_GRADLE_PROJECT_publicationName=core ./gradlew clean build publish
ORG_GRADLE_PROJECT_publicationName=generator ./gradlew publish

echo "Manually release from staging: https://oss.sonatype.org/#stagingRepositories"