#!/usr/bin/env bash

publicationName=$1

source ./secrets

./gradlew clean build

ORG_GRADLE_PROJECT_publicationName=core ./gradlew bintrayUpload
ORG_GRADLE_PROJECT_publicationName=generator ./gradlew bintrayUpload